// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8NeikD9OgxI2xUYsqssW7qMqkIBJiNUo',
    appId: '1:309434540760:android:03040415e66bd15a1cadad',
    messagingSenderId: '309434540760',
    projectId: 'edushala-c45be',
    storageBucket: 'edushala-c45be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkkDmn1kCBLpDFe5WiKf2_cnmBwAwHOA',
    appId: '1:309434540760:ios:ab38ed83d70556971cadad',
    messagingSenderId: '309434540760',
    projectId: 'edushala-c45be',
    storageBucket: 'edushala-c45be.appspot.com',
    androidClientId: '309434540760-21qb8rlp19333tkopkmcjvevmoghuca8.apps.googleusercontent.com',
    iosClientId: '309434540760-r5689jeusg3kc18252cmh605p4v4hfou.apps.googleusercontent.com',
    iosBundleId: 'com.edushala.student',
  );
}
